[build]
command = "npm install && npm run build"
builder = "NIXPACKS"

[deploy]
startCommand = "sh -c 'npm run preview -- --host 0.0.0.0 --port ${PORT:-4173}'"

[build.env]
NIXPACKS_NODE_VERSION = "20"
