version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: investigacion_dngbs
      POSTGRES_USER: investigacion_user
      POSTGRES_PASSWORD: investigacion_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend-migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://investigacion_user:investigacion_pass@db:5432/investigacion_dngbs
    depends_on:
      - db
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run db:seed
      "
    volumes:
      - ./backend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://investigacion_user:investigacion_pass@db:5432/investigacion_dngbs
      PORT: 4000
      JWT_SECRET: supersecretjwt
    depends_on:
      - backend-migrate
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE_URL: http://localhost:4000/api
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres-data:
